server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/incident_auth_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: mySuperSecretKeyForJWTGenerationMustBeLongEnough123456789
  access-expiration: 900000
  refresh-expiration: 604800000

